[widgets.mpd] Add fields `${Artists}` and `${Generes}`
vicious-widgets/vicious pull request #117
Opened 2023-12-06 01:11 UTC by toniz4

Related to #116 

Adds new return values to widgets.mpd that concatenate all artists and generes when there's more than one. For tracks with vorbis metadata.

I've also updated the docs to reflect those changes.

2023-12-07 06:39 UTC, McSinyx requested changes
The patchset looks good to me, aside from some minor formatting issues.  After you're done resolving them, could you please test if both `Artists` and `Genres` are working?

2023-12-07 15:27 UTC, toniz4 commented on widgets/mpd_all.lua
> +                            mpd_state["{Generes}"] = append_with_separator(
Done

2023-12-07 15:34 UTC, toniz4 commented
> The patchset looks good to me, aside from some minor formatting issues. After you're done resolving them, could you please test if both `Artists` and `Genres` are working?

Genres was broken before because of the typo, but now It's working fine:

Here's the output:
![image](https://github.com/vicious-widgets/vicious/assets/14265358/8a89fe4c-b4d6-4e5d-8f88-db55d7c6f849)

The update function:
```lua
local update = function (widget, args)
   if args["{state}"] == "Stop" then
      widget.visible = false
      return ''
   else
      widget.visible = true
      return {
          ('Artists: %s Track: %s Genres: %s'):format(args["{Artists}"], args["{Title}"], args["{Genres}"]),
         args["{state}"]
      }
   end
end
```

And what mpd is returning:

```
$ printf 'password ""\nstatus\ncurrentsong\nclose \n' | curl --connect-timeout 1 -fsm 3 telnet://127.0.0.1:6600
OK MPD 0.23.5
ACK [3@0] {password} incorrect password
volume: 100
repeat: 0
random: 0
single: 0
consume: 0
partition: default
playlist: 1537
playlistlength: 192
mixrampdb: 0
state: play
song: 182
songid: 1556
time: 284:321
elapsed: 284.284
bitrate: 1221
duration: 320.625
audio: 44100:16:2
nextsong: 183
nextsongid: 1557
OK
file: Parannoul/Parannoul - To See the Next Part of the Dream/01 - Beautiful World.flac
Last-Modified: 2023-02-20T06:28:07Z
Format: 44100:16:2
Title: Beautiful World
Artist: Parannoul
Album: To See the Next Part of the Dream
AlbumArtist: Parannoul
Track: 1
Disc: 1
Genre: Asian Music
Genre: K-Pop
Date: 2021-04-19
Time: 321
duration: 320.625
Pos: 182
Id: 1556
OK
```

More than one artist it's working as expected too:

![image](https://github.com/vicious-widgets/vicious/assets/14265358/1d76d1e7-14e0-460e-a3b6-d46f91af44fb)

Here I couldn't find any tracks that have multiples of other tags, not being genre, artist or albumArtist.

2023-12-08 03:25 UTC, McSinyx approved these changes
Thanks, I will merge and tag a new release this weekend.

2023-12-10 10:15 UTC, merged